### ISSUE TITLE
Support minikube-iso on OSX using xhyve

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/minikube-iso#17]
xref https://github.com/kubernetes/minikube/issues/603

**Comment by s-urbaniak** [comment]
After some debugging @zchee (author of https://github.com/zchee/docker-machine-driver-xhyve) found that xhyve probably is buggy when using newer kernels. Copying the OOB findings from kubernetes.slack.com, #minikube channel:

> zchee [7:12]  
@sur got `Initramfs unpacking failed: junk in compressed archive` error. Do you have any idea about this?

> zchee [9:33 PM]  
@sur I tried many build iso, but same.
error occur was http://lxr.free-electrons.com/source/init/initramfs.c#L497
ref:
- https://github.com/mist64/xhyve/issues/74
- https://github.com/mist64/xhyve/issues/116

**Comment by s-urbaniak** [comment]
If anyone can help debugging this, I created a dedicated image for xhyve to test this:

```
$ minikube start --vm-driver="xhyve" --memory=4096 --cpus=2 \  
    --network-plugin=cni \
    --container-runtime=rkt \
    --iso-url=https://github.com/coreos/minikube-iso/releases/download/xhyve/minikube-xhyve.iso
```

**Comment by rimusz** [comment]
@s-urbaniak I would love that to test, but I always get:
```
Starting local Kubernetes cluster...
E0927 09:12:13.196991   51932 start.go:85] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting. Retrying.
``` 
does not matter which hypervisor I choose.

**Comment by s-urbaniak** [comment]
@rimusz please also `rm -rf ~/.minikube` and any running minikube VM.

**Comment by rimusz** [comment]
@s-urbaniak tried that already, did not help

**Comment by s-urbaniak** [comment]
@rimusz do you get the same result with the released iso (https://github.com/coreos/minikube-iso/releases/download/v0.0.4/minikube-v0.0.4.iso)? Also what command line do you use?

**Comment by rimusz** [comment]
I use:
```
$ minikube start --vm-driver="xhyve" --memory=4096 --cpus=2 \  
    --network-plugin=cni \
    --container-runtime=rkt \
    --iso-url=https://github.com/coreos/minikube-iso/releases/download/xhyve/minikube-xhyve.iso
```
I'm on Sierra, but had the same minikube issues on El Capitan too

**Comment by s-urbaniak** [comment]
@rimusz well, under xhyve it doesn't work, it fails at the very beginning before even booting into the kernel, therefore we think it is a very low-level problem.

If you have troubles starting the 0.0.4 image with a different hypervisor, don't hesitate to open an issue so we can try to triage this.

**Comment by rimusz** [comment]
I do not really care about different hypervisors not working, as I prefer `xhyve` based ones only for the speed :)

**Comment by s-urbaniak** [comment]
understandable ;-) I hope we can resolve the issue soon.

**Comment by rimusz** [comment]
btw, other `xhyve` based apps work just fine for me as `docker 4 mac`, `kube-solo` and etc

**Comment by s-urbaniak** [comment]
@rimusz we are seeing this issue https://github.com/mist64/xhyve/issues/116 which is unresolved in xhyve.

**Comment by rimusz** [comment]
the problem with minikube is that it uses some old code from `mist64/xhyve#116`  and `docker 4 mac`, `kube-solo` (CoreOS based) use [docker hyperkit](https://github.com/docker/hyperkit), which does not have those issues anymore.

**Comment by dlorenc** [comment]
@rimusz I think @zchee has moved https://github.com/zchee/docker-machine-driver-xhyve over to hyperkit already.

**Comment by rimusz** [comment]
@dlorenc I had no luck to get minikube working yet

**Comment by zchee** [comment]
@s-urbaniak  @rimusz @dlorenc Yeah, my driver's stable version uses old(original?) xhyve, but now, I was switch to hyperkit.
I tested that problem uses hyperkit version's xhyve-driver, but same results. Also self-build `com.docker.hyperkit` binary.

**Comment by zchee** [comment]
@s-urbaniak @dlorenc I found a wrong point on xhyve.
As VinDuv(no mention) said,
> "Adding a sufficient offset to ramdisk_start in kexec.c allows the installer to start successfully. I have not tested it furthe"

Yeah, xhyve has put the ramdisk to the wrong memory.
I was tiny fixed `kexec.c`, cat boot https://github.com/coreos/minikube-iso/releases/download/v0.0.4/minikube-v0.0.4.iso

It's xhyve bug also hyperkit bug.
Do we report to the docker? or Do we apply own patch?

**Comment by zchee** [comment]
Ah, note that I do not know whether it is **really** a bug.
but, Certainly I was able to boot.

**Comment by dlorenc** [comment]
You're using a fork in your driver already anyway, right? How about "fixing" it in your fork and sending a PR to docker? I can help tomorrow :)

**Comment by s-urbaniak** [comment]
@zchee great news! :+1:

**Comment by zchee** [comment]
@dlorenc @s-urbaniak :D
It's very small fix.

https://github.com/docker/hyperkit/blob/master/src/firmware/kexec.c#L187
```diff
diff --git a/src/firmware/kexec.c b/src/firmware/kexec.c
index 61aeebb..a5ee627 100644
--- a/src/firmware/kexec.c
+++ b/src/firmware/kexec.c
@@ -184,7 +184,7 @@ kexec_load_ramdisk(char *path) {
 	sz = (size_t) ftell(f);
 	fseek(f, 0, SEEK_SET);
 
-	ramdisk_start = ALIGNUP((kernel.base + kernel.size), 0x1000ull);
+	ramdisk_start = ALIGNUP((kernel.base + kernel.size), 0x0210c388ull);
 
 	if ((ramdisk_start + sz) > memory.size) {
 		/* not enough memory */
```

minikube's iso(initramfs) was not broken.
It seems to be recognized to *junk* at the kexec loading because overwriting with the `ramdisk`.
It needs to be avoided that the `kernel` will be overwritten in the `ramdisk`.

The original `0x1000ull` is small for minikube-iso. but boot2docker.iso is about 41MB, minikube-iso is about 79MB, So can load the boot2docker.iso(maybe)
`0x0210c388ull` is sloppy(about? rough?) size. Maybe if larger than the size of the `kernel`, It will work.
Either way, there is a need to fix the `ramstart` to the appropriate value.

At the moment, this fix is not sufficient for pull request because it's unfounded value.
But yeah, minikube-iso can be boot :)

I will continue to read the hyperkit source. and I will pull request or create issue thread to `docker/hyperkit`.

===

Another topic.
minikube-iso required this change, So I consider add variables to `struct` instead of hardcoded `vmlinux` and `initrd.img`.
https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L51-L67
What do you think?

===

Sorry poor English :P

**Comment by zchee** [comment]
ref https://github.com/torvalds/linux/blob/master/Documentation/x86/boot.txt

**Comment by s-urbaniak** [comment]
@zchee regarding https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L51-L67, and the locations of `vmlinux`, and `initrd.img` it would be great if you could introduce variables in the `Driver` struct for those, because buildroot does not provide a simple way of reconfiguring their names.

For reference, in buildroot and thus in minikube-iso those files are called `bzImage`, and `initrd`.

**Comment by zchee** [comment]
@s-urbaniak got it.
Yeah, I know it's not simple way :( I built iso about 50 counts for this issue...
I will add those variables to `Driver` struct.
Is this better to also add command line flags?(it's not related to minikube implements?)

---

@dlorenc @s-urbaniak I created issue thread on docker/hyperkit.

**Comment by s-urbaniak** [comment]
unassigning from a release version, as it seems that we don't have to do anything in minikube-iso itself.

**Comment by s-urbaniak** [comment]
closing, as there is (at least to my knowledge) nothing to do in minikube-iso itself.
